<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260422100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Replace UTC offset timezones with IANA timezone names (DST-aware)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE country CHANGE timezone timezone VARCHAR(500) DEFAULT NULL');
        $this->addSql("UPDATE country SET timezone = CASE code
            WHEN 'AF' THEN 'Asia/Kabul'
            WHEN 'ZA' THEN 'Africa/Johannesburg'
            WHEN 'AL' THEN 'Europe/Tirane'
            WHEN 'DZ' THEN 'Africa/Algiers'
            WHEN 'DE' THEN 'Europe/Berlin'
            WHEN 'AD' THEN 'Europe/Andorra'
            WHEN 'AO' THEN 'Africa/Luanda'
            WHEN 'SA' THEN 'Asia/Riyadh'
            WHEN 'AR' THEN 'America/Argentina/Buenos_Aires'
            WHEN 'AM' THEN 'Asia/Yerevan'
            WHEN 'AU' THEN 'Australia/Perth,Australia/Darwin,Australia/Adelaide,Australia/Brisbane,Australia/Sydney'
            WHEN 'AT' THEN 'Europe/Vienna'
            WHEN 'AZ' THEN 'Asia/Baku'
            WHEN 'BE' THEN 'Europe/Brussels'
            WHEN 'BJ' THEN 'Africa/Porto-Novo'
            WHEN 'BO' THEN 'America/La_Paz'
            WHEN 'BA' THEN 'Europe/Sarajevo'
            WHEN 'BW' THEN 'Africa/Gaborone'
            WHEN 'BR' THEN 'America/Noronha,America/Belem,America/Manaus,America/Rio_Branco,America/Sao_Paulo'
            WHEN 'BG' THEN 'Europe/Sofia'
            WHEN 'BF' THEN 'Africa/Ouagadougou'
            WHEN 'BI' THEN 'Africa/Bujumbura'
            WHEN 'KH' THEN 'Asia/Phnom_Penh'
            WHEN 'CM' THEN 'Africa/Douala'
            WHEN 'CA' THEN 'America/St_Johns,America/Halifax,America/Toronto,America/Winnipeg,America/Edmonton,America/Vancouver'
            WHEN 'CL' THEN 'America/Santiago,Pacific/Easter'
            WHEN 'CN' THEN 'Asia/Shanghai'
            WHEN 'CY' THEN 'Asia/Nicosia'
            WHEN 'CO' THEN 'America/Bogota'
            WHEN 'KR' THEN 'Asia/Seoul'
            WHEN 'CR' THEN 'America/Costa_Rica'
            WHEN 'HR' THEN 'Europe/Zagreb'
            WHEN 'CU' THEN 'America/Havana'
            WHEN 'DK' THEN 'Europe/Copenhagen'
            WHEN 'EG' THEN 'Africa/Cairo'
            WHEN 'AE' THEN 'Asia/Dubai'
            WHEN 'EC' THEN 'America/Guayaquil,Pacific/Galapagos'
            WHEN 'ES' THEN 'Europe/Madrid'
            WHEN 'EE' THEN 'Europe/Tallinn'
            WHEN 'US' THEN 'America/New_York,America/Chicago,America/Denver,America/Los_Angeles,America/Anchorage,Pacific/Honolulu'
            WHEN 'FI' THEN 'Europe/Helsinki'
            WHEN 'FR' THEN 'Europe/Paris'
            WHEN 'GR' THEN 'Europe/Athens'
            WHEN 'IN' THEN 'Asia/Kolkata'
            WHEN 'ID' THEN 'Asia/Jakarta,Asia/Makassar,Asia/Jayapura'
            WHEN 'IR' THEN 'Asia/Tehran'
            WHEN 'IQ' THEN 'Asia/Baghdad'
            WHEN 'IE' THEN 'Europe/Dublin'
            WHEN 'IS' THEN 'Atlantic/Reykjavik'
            WHEN 'IL' THEN 'Asia/Jerusalem'
            WHEN 'IT' THEN 'Europe/Rome'
            WHEN 'JP' THEN 'Asia/Tokyo'
            WHEN 'JO' THEN 'Asia/Amman'
            WHEN 'KZ' THEN 'Asia/Almaty,Asia/Aqtau'
            WHEN 'KE' THEN 'Africa/Nairobi'
            WHEN 'KW' THEN 'Asia/Kuwait'
            WHEN 'LV' THEN 'Europe/Riga'
            WHEN 'LB' THEN 'Asia/Beirut'
            WHEN 'LY' THEN 'Africa/Tripoli'
            WHEN 'LT' THEN 'Europe/Vilnius'
            WHEN 'LU' THEN 'Europe/Luxembourg'
            WHEN 'MG' THEN 'Indian/Antananarivo'
            WHEN 'MY' THEN 'Asia/Kuala_Lumpur'
            WHEN 'ML' THEN 'Africa/Bamako'
            WHEN 'MA' THEN 'Africa/Casablanca'
            WHEN 'MX' THEN 'America/Mexico_City,America/Chihuahua,America/Tijuana'
            WHEN 'MC' THEN 'Europe/Monaco'
            WHEN 'MN' THEN 'Asia/Hovd,Asia/Ulaanbaatar'
            WHEN 'ME' THEN 'Europe/Podgorica'
            WHEN 'MZ' THEN 'Africa/Maputo'
            WHEN 'NA' THEN 'Africa/Windhoek'
            WHEN 'NP' THEN 'Asia/Kathmandu'
            WHEN 'NI' THEN 'America/Managua'
            WHEN 'NE' THEN 'Africa/Niamey'
            WHEN 'NG' THEN 'Africa/Lagos'
            WHEN 'NO' THEN 'Europe/Oslo'
            WHEN 'NZ' THEN 'Pacific/Auckland,Pacific/Chatham'
            WHEN 'UG' THEN 'Africa/Kampala'
            WHEN 'UZ' THEN 'Asia/Tashkent'
            WHEN 'PK' THEN 'Asia/Karachi'
            WHEN 'PA' THEN 'America/Panama'
            WHEN 'PY' THEN 'America/Asuncion'
            WHEN 'NL' THEN 'Europe/Amsterdam'
            WHEN 'PE' THEN 'America/Lima'
            WHEN 'PH' THEN 'Asia/Manila'
            WHEN 'PL' THEN 'Europe/Warsaw'
            WHEN 'PT' THEN 'Europe/Lisbon'
            WHEN 'QA' THEN 'Asia/Qatar'
            WHEN 'RO' THEN 'Europe/Bucharest'
            WHEN 'RU' THEN 'Europe/Kaliningrad,Europe/Moscow,Asia/Yekaterinburg,Asia/Krasnoyarsk,Asia/Irkutsk,Asia/Vladivostok,Asia/Kamchatka'
            WHEN 'RW' THEN 'Africa/Kigali'
            WHEN 'SN' THEN 'Africa/Dakar'
            WHEN 'RS' THEN 'Europe/Belgrade'
            WHEN 'SG' THEN 'Asia/Singapore'
            WHEN 'SK' THEN 'Europe/Bratislava'
            WHEN 'SI' THEN 'Europe/Ljubljana'
            WHEN 'SO' THEN 'Africa/Mogadishu'
            WHEN 'SD' THEN 'Africa/Khartoum'
            WHEN 'SE' THEN 'Europe/Stockholm'
            WHEN 'CH' THEN 'Europe/Zurich'
            WHEN 'SY' THEN 'Asia/Damascus'
            WHEN 'TW' THEN 'Asia/Taipei'
            WHEN 'TZ' THEN 'Africa/Dar_es_Salaam'
            WHEN 'TH' THEN 'Asia/Bangkok'
            WHEN 'TN' THEN 'Africa/Tunis'
            WHEN 'TR' THEN 'Europe/Istanbul'
            WHEN 'UA' THEN 'Europe/Kyiv'
            WHEN 'GB' THEN 'Europe/London'
            WHEN 'VE' THEN 'America/Caracas'
            WHEN 'VN' THEN 'Asia/Ho_Chi_Minh'
            WHEN 'YE' THEN 'Asia/Aden'
            WHEN 'ZM' THEN 'Africa/Lusaka'
            WHEN 'ZW' THEN 'Africa/Harare'
            WHEN 'BS' THEN 'America/Nassau'
            WHEN 'BB' THEN 'America/Barbados'
            WHEN 'BZ' THEN 'America/Belize'
            WHEN 'DM' THEN 'America/Dominica'
            WHEN 'SV' THEN 'America/El_Salvador'
            WHEN 'GD' THEN 'America/Grenada'
            WHEN 'GT' THEN 'America/Guatemala'
            WHEN 'HT' THEN 'America/Port-au-Prince'
            WHEN 'HN' THEN 'America/Tegucigalpa'
            WHEN 'JM' THEN 'America/Jamaica'
            WHEN 'KN' THEN 'America/St_Kitts'
            WHEN 'LC' THEN 'America/St_Lucia'
            WHEN 'VC' THEN 'America/St_Vincent'
            WHEN 'DO' THEN 'America/Santo_Domingo'
            WHEN 'TT' THEN 'America/Port_of_Spain'
            WHEN 'GY' THEN 'America/Guyana'
            WHEN 'SR' THEN 'America/Paramaribo'
            WHEN 'UY' THEN 'America/Montevideo'
            WHEN 'LI' THEN 'Europe/Vaduz'
            WHEN 'MK' THEN 'Europe/Skopje'
            WHEN 'MT' THEN 'Europe/Malta'
            WHEN 'MD' THEN 'Europe/Chisinau'
            WHEN 'SM' THEN 'Europe/San_Marino'
            WHEN 'VA' THEN 'Europe/Vatican'
            WHEN 'BH' THEN 'Asia/Bahrain'
            WHEN 'BD' THEN 'Asia/Dhaka'
            WHEN 'BT' THEN 'Asia/Thimphu'
            WHEN 'BN' THEN 'Asia/Brunei'
            WHEN 'GE' THEN 'Asia/Tbilisi'
            WHEN 'LA' THEN 'Asia/Vientiane'
            WHEN 'MV' THEN 'Indian/Maldives'
            WHEN 'MM' THEN 'Asia/Yangon'
            WHEN 'OM' THEN 'Asia/Muscat'
            WHEN 'LK' THEN 'Asia/Colombo'
            WHEN 'TJ' THEN 'Asia/Dushanbe'
            WHEN 'TL' THEN 'Asia/Dili'
            WHEN 'TM' THEN 'Asia/Ashgabat'
            WHEN 'CV' THEN 'Atlantic/Cape_Verde'
            WHEN 'KM' THEN 'Indian/Comoro'
            WHEN 'CG' THEN 'Africa/Brazzaville'
            WHEN 'CD' THEN 'Africa/Kinshasa,Africa/Lubumbashi'
            WHEN 'CI' THEN 'Africa/Abidjan'
            WHEN 'DJ' THEN 'Africa/Djibouti'
            WHEN 'ER' THEN 'Africa/Asmara'
            WHEN 'SZ' THEN 'Africa/Mbabane'
            WHEN 'ET' THEN 'Africa/Addis_Ababa'
            WHEN 'GA' THEN 'Africa/Libreville'
            WHEN 'GM' THEN 'Africa/Banjul'
            WHEN 'GH' THEN 'Africa/Accra'
            WHEN 'GN' THEN 'Africa/Conakry'
            WHEN 'GW' THEN 'Africa/Bissau'
            WHEN 'GQ' THEN 'Africa/Malabo'
            WHEN 'LS' THEN 'Africa/Maseru'
            WHEN 'LR' THEN 'Africa/Monrovia'
            WHEN 'MW' THEN 'Africa/Blantyre'
            WHEN 'MU' THEN 'Indian/Mauritius'
            WHEN 'MR' THEN 'Africa/Nouakchott'
            WHEN 'CF' THEN 'Africa/Bangui'
            WHEN 'ST' THEN 'Africa/Sao_Tome'
            WHEN 'SC' THEN 'Indian/Mahe'
            WHEN 'SL' THEN 'Africa/Freetown'
            WHEN 'SS' THEN 'Africa/Juba'
            WHEN 'TD' THEN 'Africa/Ndjamena'
            WHEN 'TG' THEN 'Africa/Lome'
            WHEN 'FJ' THEN 'Pacific/Fiji'
            WHEN 'MH' THEN 'Pacific/Majuro'
            WHEN 'SB' THEN 'Pacific/Guadalcanal'
            WHEN 'KI' THEN 'Pacific/Tarawa,Pacific/Enderbury,Pacific/Kiritimati'
            WHEN 'FM' THEN 'Pacific/Chuuk,Pacific/Pohnpei'
            WHEN 'NR' THEN 'Pacific/Nauru'
            WHEN 'PW' THEN 'Pacific/Palau'
            WHEN 'PG' THEN 'Pacific/Port_Moresby'
            WHEN 'WS' THEN 'Pacific/Apia'
            WHEN 'TO' THEN 'Pacific/Tongatapu'
            WHEN 'TV' THEN 'Pacific/Funafuti'
            WHEN 'VU' THEN 'Pacific/Efate'
            WHEN 'HU' THEN 'Europe/Budapest'
            WHEN 'CZ' THEN 'Europe/Prague'
            WHEN 'BY' THEN 'Europe/Minsk'
            WHEN 'KG' THEN 'Asia/Bishkek'
            WHEN 'KP' THEN 'Asia/Pyongyang'
            WHEN 'AG' THEN 'America/Antigua'
            WHEN 'HK' THEN 'Asia/Hong_Kong'
            WHEN 'MO' THEN 'Asia/Macau'
            WHEN 'XK' THEN 'Europe/Belgrade'
            WHEN 'PS' THEN 'Asia/Gaza,Asia/Hebron'
            WHEN 'GP' THEN 'America/Guadeloupe'
            WHEN 'MQ' THEN 'America/Martinique'
            WHEN 'GF' THEN 'America/Cayenne'
            WHEN 'RE' THEN 'Indian/Reunion'
            WHEN 'YT' THEN 'Indian/Mayotte'
            WHEN 'NC' THEN 'Pacific/Noumea'
            WHEN 'PF' THEN 'Pacific/Gambier,Pacific/Marquesas,Pacific/Tahiti'
            WHEN 'PM' THEN 'America/Miquelon'
            WHEN 'BL' THEN 'America/St_Barthelemy'
            WHEN 'MF' THEN 'America/Marigot'
            WHEN 'WF' THEN 'Pacific/Wallis'
            WHEN 'AW' THEN 'America/Aruba'
            WHEN 'CW' THEN 'America/Curacao'
            WHEN 'KY' THEN 'America/Cayman'
            WHEN 'BM' THEN 'Atlantic/Bermuda'
            WHEN 'VG' THEN 'America/Tortola'
            WHEN 'TC' THEN 'America/Grand_Turk'
            WHEN 'PR' THEN 'America/Puerto_Rico'
            WHEN 'GI' THEN 'Europe/Gibraltar'
            WHEN 'FO' THEN 'Atlantic/Faroe'
            WHEN 'GL' THEN 'America/Nuuk,America/Scoresbysund,America/Thule'
            WHEN 'JE' THEN 'Europe/Jersey'
            WHEN 'GG' THEN 'Europe/Guernsey'
            WHEN 'IM' THEN 'Europe/Isle_of_Man'
            WHEN 'FK' THEN 'Atlantic/Stanley'
            WHEN 'CK' THEN 'Pacific/Rarotonga'
            ELSE timezone
        END");
    }

    public function down(Schema $schema): void
    {
    }
}
