<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260110192925 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql("INSERT INTO currency (code, name, symbol) VALUES
('USD', 'Dollar américain', '$'),
('AED', 'Dirham des Émirats arabes unis', 'د.إ'),
('AFN', 'Afghani afghan', '؋'),
('ALL', 'Lek albanais', 'L'),
('AMD', 'Dram arménien', '֏'),
('ANG', 'Florin des Antilles néerlandaises', 'ƒ'),
('AOA', 'Kwanza angolais', 'Kz'),
('ARS', 'Peso argentin', '$'),
('AUD', 'Dollar australien', 'A$'),
('AWG', 'Florin arubais', 'ƒ'),
('AZN', 'Manat azerbaïdjanais', '₼'),
('BAM', 'Mark convertible de Bosnie-Herzégovine', 'KM'),
('BBD', 'Dollar barbadien', 'Bds$'),
('BDT', 'Taka bangladais', '৳'),
('BGN', 'Lev bulgare', 'лв'),
('BHD', 'Dinar bahreïni', '.د.ب'),
('BIF', 'Franc burundais', 'FBu'),
('BMD', 'Dollar bermudien', '$'),
('BND', 'Dollar de Brunei', 'B$'),
('BOB', 'Boliviano bolivien', 'Bs.'),
('BRL', 'Real brésilien', 'R$'),
('BSD', 'Dollar bahaméen', 'B$'),
('BTN', 'Ngultrum bhoutanais', 'Nu.'),
('BWP', 'Pula botswanais', 'P'),
('BYN', 'Rouble biélorusse', 'Br'),
('BZD', 'Dollar bélizien', 'BZ$'),
('CAD', 'Dollar canadien', 'C$'),
('CDF', 'Franc congolais', 'FC'),
('CHF', 'Franc suisse', 'CHF'),
('CLF', 'Unité d''investissement chilienne', 'UF'),
('CLP', 'Peso chilien', '$'),
('CNH', 'Yuan chinois (offshore)', '¥'),
('CNY', 'Yuan chinois', '¥'),
('COP', 'Peso colombien', '$'),
('CRC', 'Colón costaricain', '₡'),
('CUP', 'Peso cubain', '₱'),
('CVE', 'Escudo cap-verdien', '$'),
('CZK', 'Couronne tchèque', 'Kč'),
('DJF', 'Franc djiboutien', 'Fdj'),
('DKK', 'Couronne danoise', 'kr'),
('DOP', 'Peso dominicain', 'RD$'),
('DZD', 'Dinar algérien', 'د.ج'),
('EGP', 'Livre égyptienne', '£'),
('ERN', 'Nakfa érythréen', 'Nfk'),
('ETB', 'Birr éthiopien', 'Br'),
('EUR', 'Euro', '€'),
('FJD', 'Dollar fidjien', 'FJ$'),
('FKP', 'Livre des Îles Falkland', '£'),
('FOK', 'Couronne féroïenne', 'kr'),
('GBP', 'Livre sterling', '£'),
('GEL', 'Lari géorgien', '₾'),
('GGP', 'Livre de Guernesey', '£'),
('GHS', 'Cedi ghanéen', '₵'),
('GIP', 'Livre de Gibraltar', '£'),
('GMD', 'Dalasi gambien', 'D'),
('GNF', 'Franc guinéen', 'FG'),
('GTQ', 'Quetzal guatémaltèque', 'Q'),
('GYD', 'Dollar guyanien', 'G$'),
('HKD', 'Dollar de Hong Kong', 'HK$'),
('HNL', 'Lempira hondurien', 'L'),
('HRK', 'Kuna croate', 'kn'),
('HTG', 'Gourde haïtienne', 'G'),
('HUF', 'Forint hongrois', 'Ft'),
('IDR', 'Roupie indonésienne', 'Rp'),
('ILS', 'Shekel israélien', '₪'),
('IMP', 'Livre de l''Île de Man', '£'),
('INR', 'Roupie indienne', '₹'),
('IQD', 'Dinar irakien', 'ع.د'),
('IRR', 'Rial iranien', '﷼'),
('ISK', 'Couronne islandaise', 'kr'),
('JEP', 'Livre de Jersey', '£'),
('JMD', 'Dollar jamaïcain', 'J$'),
('JOD', 'Dinar jordanien', 'د.ا'),
('JPY', 'Yen japonais', '¥'),
('KES', 'Shilling kényan', 'KSh'),
('KGS', 'Som kirghize', 'лв'),
('KHR', 'Riel cambodgien', '៛'),
('KID', 'Dollar de Kiribati', '$'),
('KMF', 'Franc comorien', 'CF'),
('KRW', 'Won sud-coréen', '₩'),
('KWD', 'Dinar koweïtien', 'د.ك'),
('KYD', 'Dollar des Îles Caïmans', 'CI$'),
('KZT', 'Tenge kazakh', '₸'),
('LAK', 'Kip laotien', '₭'),
('LBP', 'Livre libanaise', 'ل.ل'),
('LKR', 'Roupie srilankaise', 'Rs'),
('LRD', 'Dollar libérien', 'L$'),
('LSL', 'Loti lesothien', 'L'),
('LYD', 'Dinar libyen', 'ل.د'),
('MAD', 'Dirham marocain', 'د.م.'),
('MDL', 'Leu moldave', 'L'),
('MGA', 'Ariary malgache', 'Ar'),
('MKD', 'Denar macédonien', 'ден'),
('MMK', 'Kyat birman', 'K'),
('MNT', 'Tögrög mongol', '₮'),
('MOP', 'Pataca macanaise', 'MOP$'),
('MRU', 'Ouguiya mauritanien', 'UM'),
('MUR', 'Roupie mauricienne', '₨'),
('MVR', 'Rufiyaa maldivien', 'ރ.'),
('MWK', 'Kwacha malawien', 'MK'),
('MXN', 'Peso mexicain', '$'),
('MYR', 'Ringgit malaisien', 'RM'),
('MZN', 'Metical mozambicain', 'MT'),
('NAD', 'Dollar namibien', 'N$'),
('NGN', 'Naira nigérian', '₦'),
('NIO', 'Córdoba nicaraguayen', 'C$'),
('NOK', 'Couronne norvégienne', 'kr'),
('NPR', 'Roupie népalaise', '₨'),
('NZD', 'Dollar néo-zélandais', 'NZ$'),
('OMR', 'Rial omanais', 'ر.ع.'),
('PAB', 'Balboa panaméen', 'B/.'),
('PEN', 'Sol péruvien', 'S/.'),
('PGK', 'Kina de Papouasie-Nouvelle-Guinée', 'K'),
('PHP', 'Peso philippin', '₱'),
('PKR', 'Roupie pakistanaise', '₨'),
('PLN', 'Zloty polonais', 'zł'),
('PYG', 'Guaraní paraguayen', '₲'),
('QAR', 'Riyal qatarien', 'ر.ق'),
('RON', 'Leu roumain', 'lei'),
('RSD', 'Dinar serbe', 'дин.'),
('RUB', 'Rouble russe', '₽'),
('RWF', 'Franc rwandais', 'FRw'),
('SAR', 'Riyal saoudien', 'ر.س'),
('SBD', 'Dollar des Îles Salomon', 'SI$'),
('SCR', 'Roupie seychelloise', '₨'),
('SDG', 'Livre soudanaise', 'ج.س.'),
('SEK', 'Couronne suédoise', 'kr'),
('SGD', 'Dollar de Singapour', 'S$'),
('SHP', 'Livre de Sainte-Hélène', '£'),
('SLE', 'Leone sierra-léonais', 'Le'),
('SLL', 'Leone sierra-léonais (ancien)', 'Le'),
('SOS', 'Shilling somalien', 'Sh'),
('SRD', 'Dollar surinamais', '$'),
('SSP', 'Livre sud-soudanaise', '£'),
('STN', 'Dobra santoméen', 'Db'),
('SYP', 'Livre syrienne', '£'),
('SZL', 'Lilangeni swazi', 'L'),
('THB', 'Baht thaïlandais', '฿'),
('TJS', 'Somoni tadjik', 'ЅМ'),
('TMT', 'Manat turkmène', 'm'),
('TND', 'Dinar tunisien', 'د.ت'),
('TOP', 'Pa''anga tongien', 'T$'),
('TRY', 'Livre turque', '₺'),
('TTD', 'Dollar de Trinité-et-Tobago', 'TT$'),
('TVD', 'Dollar tuvaluan', '$'),
('TWD', 'Dollar taïwanais', 'NT$'),
('TZS', 'Shilling tanzanien', 'TSh'),
('UAH', 'Hryvnia ukrainienne', '₴'),
('UGX', 'Shilling ougandais', 'USh'),
('UYU', 'Peso uruguayen', '\$U'),
('UZS', 'Sum ouzbek', 'so''m'),
('VES', 'Bolívar vénézuélien', 'Bs.'),
('VND', 'Dong vietnamien', '₫'),
('VUV', 'Vatu vanuatuan', 'VT'),
('WST', 'Tala samoan', 'WS$'),
('XAF', 'Franc CFA (BEAC)', 'FCFA'),
('XCD', 'Dollar des Caraïbes orientales', 'EC$'),
('XCG', 'Florin caribéen', 'ƒ'),
('XDR', 'Droit de tirage spécial (FMI)', 'XDR'),
('XOF', 'Franc CFA (BCEAO)', 'CFA'),
('XPF', 'Franc CFP', '₣'),
('YER', 'Rial yéménite', '﷼'),
('ZAR', 'Rand sud-africain', 'R'),
('ZMW', 'Kwacha zambien', 'ZK'),
('ZWG', 'Dollar zimbabwéen (Or)', 'Z$'),
('ZWL', 'Dollar zimbabwéen', 'Z$');");
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
    }
}
